spring:
  datasource:
    url: jdbc:mysql://10.48.0.13:3306/TestPlatform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://10.48.0.13:3306/TestPlatform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useServerPrepStmts=true&cachePrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=false
    username: insp_dev
    password: insp_dev@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false
  application:
    admin:
      enabled: false
endpoints:
  jmx:
    enabled: false

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.testing.automation.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.testing.automation.Mapper: INFO
    root: INFO
    com.testing.automation: DEBUG
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.pool: DEBUG
    com.mysql: DEBUG
    org.springframework.jdbc: DEBUG

server:
  port: 7777

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
    jmx:
      exposure:
        exclude: "*"
  metrics:
    export:
      prometheus:
        enabled: false

# AI Configuration
ai:
  gemini:
    api-key: ${GEMINI_API_KEY:AIzaSyD-Onf62LYaxRDEbwMliUo3tw0uATrEZrE}
    #AIzaSyD-Onf62LYaxRDEbwMliUo3tw0uATrEZrE
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
