spring:
  datasource:
    url: jdbc:mysql://10.48.0.13:3306/TestPlatform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: insp_dev
    password: insp_dev@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
  jmx:
    enabled: false
  application:
    admin:
      enabled: false
endpoints:
  jmx:
    enabled: false

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.testing.automation.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.testing.automation.mapper: INFO
    root: INFO
    com.testing.automation: DEBUG
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.pool: DEBUG
    com.mysql: DEBUG
    org.springframework.jdbc: DEBUG

server:
  port: 7777

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    jmx:
      exposure:
        exclude: "*"
  metrics:
    export:
      prometheus:
        enabled: true
