spring:
  datasource:
    url: jdbc:mysql://10.48.0.13:3306/TestPlatform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: insp_dev
    password: insp_dev@123
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    enabled: false
  application:
    admin:
      enabled: false
endpoints:
  jmx:
    enabled: false

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.testing.automation.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.testing.automation.mapper: INFO # 添加这行来查看SQL语句
    root: INFO
    com.testing.automation: DEBUG
    com.zaxxer.hikari: INFO
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 7777

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    jmx:
      exposure:
        exclude: "*"
  metrics:
    export:
      prometheus:
        enabled: true
